# Site settings
title: SeanAbu 
header-img: img/home-bg.jpg
email: seanabu.wilson@gmail.com
description: "Just a few posts to share my work as a data scientist with you."
baseurl: ""
url: "http://seanabu.com"
twitter_username: SeanAbu
github_username:  SeanAbu
facebook_username:  SeanAbu

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
